### ISSUE TITLE
[Bug]: `OnedarkproCache` occassionally hangs Neovim

### ISSUE THREAD

**Issue by mrjones2014** [olimorris/onedarkpro.nvim#112] opened 2022-10-12 13:03 UTC
### Your OneDarkPro config

```lua
return {
  'olimorris/onedarkpro.nvim',
  config = function()
    local onedarkpro = require('onedarkpro')
    local utils = require('onedarkpro.lib.color')
    local dark_gray = utils.lighten('#000000', 0.01, '#101010')
    local normal_fg = '#abb2bf'
    local buffer_inactive = '#434852'
    onedarkpro.setup({
      dark_theme = 'onedark_dark',
      caching = true,
      colors = {
        telescope_prompt = dark_gray,
        telescope_results = '#000000',
        comment = onedarkpro.get_colors('onedark_vivid').gray,
      },
      highlights = {
        CmdLine = {
          bg = dark_gray,
          fg = normal_fg,
        },
        LineNr = '${color_column}',
        SignColumn = '${color_column}',
        Search = {
          fg = '${black}',
          bg = '${highlight}',
        },
        TelescopeBorder = {
          fg = '${telescope_results}',
          bg = '${telescope_results}',
        },
        TelescopePromptBorder = {
          fg = '${telescope_prompt}',
          bg = '${telescope_prompt}',
        },
        TelescopePromptCounter = { fg = '${fg}' },
        TelescopePromptNormal = { fg = '${fg}', bg = '${telescope_prompt}' },
        TelescopePromptPrefix = {
          fg = '${green}',
          bg = '${telescope_prompt}',
        },
        TelescopePromptTitle = {
          fg = '${telescope_prompt}',
          bg = '${green}',
        },

        TelescopePreviewTitle = {
          fg = '${telescope_results}',
          bg = '${green}',
        },
        TelescopeResultsTitle = {
          fg = '${telescope_results}',
          bg = '${telescope_results}',
        },

        TelescopeMatching = { fg = '${green}' },
        TelescopeNormal = { bg = '${telescope_results}' },
        TelescopeSelection = { bg = '${telescope_prompt}' },

        -- barbar.nvim
        BufferCurrent = { fg = normal_fg, style = 'bold,italic' },
        BufferCurrentMod = { fg = normal_fg, style = 'bold,italic' },
        BufferInactiveSign = { fg = buffer_inactive },
      },
      plugins = {
        gitsigns = true,
        indentline = true,
        neotest = true,
        nvim_cmp = true,
        native_lsp = true,
        nvim_tree = true,
        nvim_ts_rainbow = true,
        op_nvim = true,
        packer = true,
        trouble = true,
      },
      options = {
        bold = true,
        italic = true,
        undercurl = true,
        window_unfocused_color = true,
      },
      styles = {
        comments = 'italic',
        keywords = 'italic',
      },
    })
    vim.cmd.colorscheme('onedarkpro')
  end,
}
```

### Error messages

none

### What I expect to happen

It compiles cache

### What actually happens

Not very often, but every once in a while, `:OnedarkproCache` will hang Neovim and I have to kill it with `killall -KILL nvim`

### Reproduce the bug

I'm not sure any consistent way to reproduce, sorry. It happens maybe every 1 in 10-20 times if I had to estimate.

Run `:OnedarkproCache` a bunch of times until it reproduces.

### Final checks

- [X] I have made sure that the colorscheme's caching is not the issue
- [X] I have made sure this is not a duplicate issue
- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`

**Comment by mmirus** [comment] 2022-10-12 14:52
I hit this a number of times, as well. Eventually it did begin responding again. I don't have any more precise way to reproduce than you (and I'm not using the cache currently, since it doesn't support the legacy ft_highlights).

**Comment by olimorris** [comment] 2022-10-12 15:44
I wonder if this is something to do with writing to file...

What I propose is that I'll add some debugging to the colorscheme in the coming days and we can see where it hangs based on what's logged.

**Comment by mrjones2014** [comment] 2022-10-12 15:48
Another somewhat related issue is that if there is an error in the cached file, then a lot of the rest of the theme fails to load, e.g. you cannot regenerate the cache because the `:OnedarkproCache` command doesn't get defined.

I think that bit should be basically wrapping the cache loading in [`pcall`](https://www.lua.org/pil/8.4.html)

**Comment by olimorris** [comment] 2022-10-12 16:16
That's a really great spot!

**Comment by olimorris** [comment] 2022-10-13 13:36
@mrjones2014 can you set `log_level = "debug"` in your configuration? A `onedarkpro.log` file should be generated in `~/.local/state/nvim/`.

**Comment by mrjones2014** [comment] 2022-10-13 13:38
Sure. I'll post back here if I notice the issue again.

**Comment by olimorris** [comment] 2022-12-08 18:34
Closing this after the new merge. Please re-open if you notice any performance issues.

**Closed by olimorris** 2022-12-08 18:34 UTC
Labels: bug, awaiting response
